name: "sfdx"

on: 
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Install Salesforce CLI'
        run: |
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx-cli
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1 
          ./sfdx-cli/install
       # Runs a set of commands using the runners shell
      - name: 'Decrypt file'
     #   run: openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out server.key -base64 -K  "E5E9FA1BA31ECD1AE84F75CAAA474F3A663F05F412028F81DA65D26EE56424B2" -iv "E93DA465B309C53FEC5FF93C9637DA58^C"
        run: openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out server.key -base64 -K  "E5E9FA1BA31ECD1AE84F75CAAA474F3A663F05F412028F81DA65D26EE56424B2" -iv "E93DA465B309C53FEC5FF93C9637DA58^C"
        env:
         DECRYPTION_KEY: ${{ secrets.DECRYPTION_KEY }}
         DECRYPTION_IV: ${{ secrets.DECRYPTION_IV }}
      - name: 'Create the key & authorise dev Hub'
        run: 'sfdx force:auth:jwt:grant --clientid="3MVG9t0sl2P.pBypl07KvI.FUHkU1Hw6_7JdMUcR4O4vtd51XoD01z0JyibB.CUjGip1YlyEyHg.MK7GSgUNq"  --username=meri.wa@gmail.com --jwtkeyfile server.key --setdefaultdevhubusername --setalias=hub-org'
        env:
         CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
         USERNAME: ${{ secrets.USERNAME }}
      #- name: Create scratch org
        #run: "sfdx force:org:create  --setdefaultusername -f config/project-scratch-def.json -a my-scratch --setalias soenv"
      #- name: Password generation !
       # run: "sfdx force:user:password:generate --targetusername soenv"
        # push source into scratch org
      #- name: Push source
      #  run: "sfdx force:source:push -u hub-org"
      - name: 'List orgs'
        run: "sfdx force:org:list"
        # run tests 
      - name: 'Run tests'
        run: "sfdx force:apex:test:run -u hub-org --resultformat human"
      - name: 'Get scratch Org URL'
        id: out-cache
        run: echo ::set-output name=orgCreateResult::$(sfdx force:org:display --json -u soenv)
        # get URL and params of scratch org
      - name: 'Get Scratch URL'
        id: params
        run: |
          echo ::set-output name=instanceURL::$(echo $orgCreateResult | jq -r .result.instanceUrl)
          echo ::set-output name=accessToken::$(echo $orgCreateResult | jq -r .result.accessToken)
          echo ::set-output name=parameters::'/secur/frontdoor.jsp?sid='
        env:
          orgCreateResult: ${{ steps.out-cache.outputs.orgCreateResult}}
        #comment Pull
      - name: 'Comment on pull request'
        uses: unsplash/comment-on-pr@master
        with:
          msg: ${{steps.params.outputs.instanceURL}}${{steps.params.outputs.parameters}}${{steps.params.outputs.accessToken}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: 'Run Merge'
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: Merged
          target_branch: master
          github_token: ${{ github.token }}
      - name: Checking your input
        run: |
          echo "github.event.pull_request.merged           : $MERGED_RAW"
          echo "github.event.pull_request.merged == 'true' : $MERGED_TRUE_STR"
          echo "github.event.pull_request.merged  == true  : $MERGED_TRUE_BOOL"
          echo "github.action ==closed                     : $MERGED_CLOSED"
        env:
          MERGED_RAW: ${{ github.event.pull_request.merged }}
          MERGED_TRUE_STR: ${{ github.event.pull_request.merged == 'true' }}
          MERGED_TRUE_BOOL: ${{ github.event.pull_request.merged == true }}
          MERGED_CLOSED: ${{ github.action }}
      - name: 'Convert Metadata'
        run: "sfdx force:source:convert --rootdir=force-app --outputdir=convert"
      - name: 'Run Test on Metadata'
        run: sfdx force:mdapi:deploy --wait 62 --deploydir=convert --testlevel=RunLocalTests --checkonly -u hub-org 
      - name: 'Run deploy success'
        run: "sfdx force:mdapi:deploy --wait 62 --deploydir=convert --testlevel=RunLocalTests -u hub-org"
      - name: 'Run Deployement Report success'
        run: "sfdx force:mdapi:deploy:report -u  hub-org --verbose"
